// ============================================================
// Kasana Watches — Shared Product Data
// Single source of truth for watch catalog, categories, and metadata.
// ============================================================

export const watchesData = {
    men: [
        {
            id: 1,
            name: "Chronograph Elite",
            price: 24999,
            originalPrice: 29999,
            image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800",
                "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&q=80&w=800",
                "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.8,
            reviews: 124,
            isNew: true,
            isSale: false,
            description: "The Chronograph Elite represents the pinnacle of precision engineering. Crafted with meticulous attention to detail, this timepiece features a Swiss-made automatic movement, sapphire crystal glass, and a 42mm stainless steel case. Perfect for the modern gentleman who appreciates both style and functionality.",
            features: [
                "Swiss Automatic Movement",
                "Sapphire Crystal Glass",
                "42mm Stainless Steel Case",
                "Water Resistant 100m",
                "Luminous Hands & Markers",
                "Date Display",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "42mm",
                dialColor: "Black",
                strapMaterial: "Genuine Leather",
                movement: "Swiss Automatic",
                waterResistance: "100m",
                warranty: "2 Years International",
            },
        },
        {
            id: 2,
            name: "Midnight Classic",
            price: 18999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&q=80&w=800",
                "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.9,
            reviews: 89,
            isNew: false,
            isSale: false,
            description: "Embrace timeless elegance with the Midnight Classic. This sophisticated timepiece combines classic design elements with modern reliability. The deep midnight blue dial catches light beautifully, while the premium leather strap ensures all-day comfort.",
            features: [
                "Japanese Quartz Movement",
                "Hardened Mineral Crystal",
                "40mm Case Diameter",
                "Water Resistant 50m",
                "Quick-Release Strap",
                "Date Window",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "40mm",
                dialColor: "Midnight Blue",
                strapMaterial: "Italian Leather",
                movement: "Japanese Quartz",
                waterResistance: "50m",
                warranty: "2 Years International",
            },
        },
        {
            id: 3,
            name: "Royal Automatic",
            price: 42999,
            originalPrice: 49999,
            image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&q=80&w=800",
                "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 5.0,
            reviews: 201,
            isNew: false,
            isSale: true,
            description: "The Royal Automatic is a masterpiece of horological excellence. Featuring an exhibition caseback that reveals the intricate automatic movement, this watch is as much a conversation piece as it is a precision timekeeping instrument.",
            features: [
                "Automatic Self-Winding",
                "Exhibition Caseback",
                "Sapphire Crystal",
                "Power Reserve 42 Hours",
                "Anti-Reflective Coating",
                "Skeleton Dial Design",
            ],
            specs: {
                caseMaterial: "316L Stainless Steel",
                caseSize: "44mm",
                dialColor: "Silver Skeleton",
                strapMaterial: "Stainless Steel Bracelet",
                movement: "Automatic",
                waterResistance: "100m",
                warranty: "3 Years International",
            },
        },
        {
            id: 4,
            name: "Vintage Heritage",
            price: 31999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.7,
            reviews: 56,
            isNew: true,
            isSale: false,
            description: "Inspired by the golden age of watchmaking, the Vintage Heritage pays homage to classic designs while incorporating modern technology. The aged brass accents and cream dial create a nostalgic yet refined aesthetic.",
            features: [
                "Vintage-Inspired Design",
                "Domed Crystal",
                "Cathedral Hands",
                "Aged Brass Accents",
                "See-Through Caseback",
                "Roman Numerals",
            ],
            specs: {
                caseMaterial: "Bronze & Steel",
                caseSize: "38mm",
                dialColor: "Cream",
                strapMaterial: "Distressed Leather",
                movement: "Swiss Automatic",
                waterResistance: "30m",
                warranty: "2 Years International",
            },
        },
        {
            id: 5,
            name: "Sport Titanium",
            price: 27999,
            originalPrice: 32999,
            image: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.6,
            reviews: 178,
            isNew: false,
            isSale: true,
            description: "Engineered for the active lifestyle, the Sport Titanium is incredibly lightweight yet remarkably durable. The titanium construction is hypoallergenic and resistant to corrosion, making it the perfect companion for any adventure.",
            features: [
                "Grade 5 Titanium Case",
                "Rotating Bezel",
                "Super-LumiNova",
                "Screw-Down Crown",
                "Silicone Strap",
                "Chronograph Function",
            ],
            specs: {
                caseMaterial: "Titanium",
                caseSize: "43mm",
                dialColor: "Black",
                strapMaterial: "Silicone Rubber",
                movement: "Japanese Quartz Chrono",
                waterResistance: "200m",
                warranty: "2 Years International",
            },
        },
        {
            id: 6,
            name: "Executive Pro",
            price: 55999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.9,
            reviews: 92,
            isNew: false,
            isSale: false,
            description: "The Executive Pro is designed for those who demand excellence in every aspect of life. This premium timepiece features an 18K rose gold case and a sophisticated grey sunray dial that exudes luxury and refinement.",
            features: [
                "18K Rose Gold Case",
                "Sunray Dial Finish",
                "Swiss Automatic",
                "Alligator Leather Strap",
                "Folding Clasp",
                "Moon Phase Complication",
            ],
            specs: {
                caseMaterial: "18K Rose Gold",
                caseSize: "41mm",
                dialColor: "Grey Sunray",
                strapMaterial: "Alligator Leather",
                movement: "Swiss Automatic",
                waterResistance: "50m",
                warranty: "5 Years International",
            },
        },
        {
            id: 7,
            name: "Urban Steel",
            price: 15999,
            originalPrice: 19999,
            image: "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1612817159949-195b6eb9e31a?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.5,
            reviews: 245,
            isNew: false,
            isSale: true,
            description: "Urban Steel brings contemporary style to your wrist. The minimalist design with a clean dial and mesh bracelet makes it versatile enough for both casual and formal occasions.",
            features: [
                "Minimalist Design",
                "Mesh Steel Bracelet",
                "Ultra-Thin Profile",
                "Japanese Movement",
                "Quick-Adjust Clasp",
                "Scratch-Resistant Crystal",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "39mm",
                dialColor: "White",
                strapMaterial: "Mesh Steel",
                movement: "Japanese Quartz",
                waterResistance: "30m",
                warranty: "2 Years International",
            },
        },
        {
            id: 8,
            name: "Carbon Noir",
            price: 38999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.8,
            reviews: 67,
            isNew: true,
            isSale: false,
            description: "The Carbon Noir represents cutting-edge materials science. The carbon fiber case is incredibly lightweight while being stronger than steel. The all-black aesthetic with red accents creates a bold, modern statement.",
            features: [
                "Carbon Fiber Case",
                "DLC Coated Bezel",
                "Red Accent Details",
                "Automatic Movement",
                "Kevlar Strap",
                "Anti-Magnetic",
            ],
            specs: {
                caseMaterial: "Carbon Fiber",
                caseSize: "45mm",
                dialColor: "Black with Red Accents",
                strapMaterial: "Kevlar",
                movement: "Swiss Automatic",
                waterResistance: "100m",
                warranty: "3 Years International",
            },
        },
    ],
    women: [
        {
            id: 1,
            name: "Rose Gold Elegance",
            price: 22999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1548169874-53e85f753f1e?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1548169874-53e85f753f1e?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.9,
            reviews: 156,
            isNew: true,
            isSale: false,
            description: "The Rose Gold Elegance is a celebration of feminine grace. The warm rose gold tones complement every skin tone, while the mother-of-pearl dial adds an ethereal quality to this stunning timepiece.",
            features: [
                "Rose Gold PVD Coating",
                "Mother-of-Pearl Dial",
                "Swarovski Crystal Markers",
                "Swiss Quartz Movement",
                "Jewelry Clasp",
                "Slim Profile Design",
            ],
            specs: {
                caseMaterial: "Rose Gold PVD Steel",
                caseSize: "32mm",
                dialColor: "Mother of Pearl",
                strapMaterial: "Mesh Rose Gold",
                movement: "Swiss Quartz",
                waterResistance: "30m",
                warranty: "2 Years International",
            },
        },
        {
            id: 2,
            name: "Diamond Luxe",
            price: 65999,
            originalPrice: 75999,
            image: "https://images.unsplash.com/photo-1612347519529-5b3e1e3d9b8c?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1612347519529-5b3e1e3d9b8c?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 5.0,
            reviews: 78,
            isNew: false,
            isSale: true,
            description: "Adorned with genuine diamonds, the Diamond Luxe is the epitome of luxury. Each stone is hand-set by master jewelers, creating a timepiece that sparkles with every movement.",
            features: [
                "Genuine Diamond Bezel",
                "Hand-Set Stones",
                "18K White Gold Case",
                "Swiss Automatic",
                "Sapphire Crystal",
                "Limited Edition",
            ],
            specs: {
                caseMaterial: "18K White Gold",
                caseSize: "28mm",
                dialColor: "Silver Diamond",
                strapMaterial: "Satin",
                movement: "Swiss Automatic",
                waterResistance: "30m",
                warranty: "5 Years International",
            },
        },
        {
            id: 3,
            name: "Pearl Classic",
            price: 28999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1619134778706-7015533a6150?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1619134778706-7015533a6150?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.8,
            reviews: 134,
            isNew: false,
            isSale: false,
            description: "The Pearl Classic features a genuine mother-of-pearl dial that showcases nature's artistry. Each dial is unique, with subtle iridescent patterns that shift in the light.",
            features: [
                "Genuine Mother-of-Pearl",
                "Roman Numeral Markers",
                "Slim Leather Strap",
                "Japanese Movement",
                "Crystal Accents",
                "Date Display",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "30mm",
                dialColor: "Iridescent Pearl",
                strapMaterial: "Leather",
                movement: "Japanese Quartz",
                waterResistance: "30m",
                warranty: "2 Years International",
            },
        },
        {
            id: 4,
            name: "Silver Petite",
            price: 16999,
            originalPrice: 21999,
            image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.7,
            reviews: 201,
            isNew: false,
            isSale: true,
            description: "Delicate and refined, the Silver Petite is designed for the modern minimalist. The compact case size and clean lines make it perfect for everyday elegance.",
            features: [
                "Petite 26mm Case",
                "Silver Sunray Dial",
                "Interchangeable Straps",
                "Japanese Movement",
                "Dainty Design",
                "Gift Box Included",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "26mm",
                dialColor: "Silver Sunray",
                strapMaterial: "Leather",
                movement: "Japanese Quartz",
                waterResistance: "30m",
                warranty: "2 Years International",
            },
        },
        {
            id: 5,
            name: "Sapphire Dream",
            price: 48999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1549972574-20eb06fac9cc?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1549972574-20eb06fac9cc?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.9,
            reviews: 89,
            isNew: true,
            isSale: false,
            description: "The Sapphire Dream features a stunning deep blue dial reminiscent of the ocean's depths. The sapphire accents around the bezel add a touch of precious beauty.",
            features: [
                "Sapphire Crystal Bezel",
                "Deep Blue Dial",
                "Swiss Movement",
                "Stainless Steel Case",
                "Blue Leather Strap",
                "Date Complication",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "34mm",
                dialColor: "Deep Blue",
                strapMaterial: "Blue Leather",
                movement: "Swiss Quartz",
                waterResistance: "50m",
                warranty: "3 Years International",
            },
        },
        {
            id: 6,
            name: "Velvet Night",
            price: 34999,
            originalPrice: 39999,
            image: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.6,
            reviews: 112,
            isNew: false,
            isSale: true,
            description: "Velvet Night embodies sophisticated glamour. The deep black dial with starlight markers creates a celestial effect, while the velvet strap adds a luxurious tactile experience.",
            features: [
                "Starlight Markers",
                "Velvet Strap",
                "Black PVD Case",
                "Swiss Movement",
                "Crystal Crown",
                "Moon Phase",
            ],
            specs: {
                caseMaterial: "Black PVD Steel",
                caseSize: "32mm",
                dialColor: "Black Starlight",
                strapMaterial: "Velvet",
                movement: "Swiss Quartz",
                waterResistance: "30m",
                warranty: "2 Years International",
            },
        },
    ],
    couples: [
        {
            id: 1,
            name: "Eternal Bond Set",
            price: 45999,
            originalPrice: 54999,
            image: "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 5.0,
            reviews: 234,
            isNew: true,
            isSale: true,
            description: "The Eternal Bond Set celebrates love with a pair of perfectly matched timepieces. The his and hers designs share common elements while each maintaining their own character.",
            features: [
                "Matching Design Elements",
                "His & Hers Set",
                "Premium Gift Box",
                "Certificate of Authenticity",
                "Engraving Available",
                "Lifetime Service",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "40mm / 32mm",
                dialColor: "Champagne",
                strapMaterial: "Leather",
                movement: "Swiss Quartz",
                waterResistance: "50m",
                warranty: "Lifetime Limited",
            },
        },
        {
            id: 2,
            name: "Classic Duo",
            price: 38999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1539874754764-5a96559165b0?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.8,
            reviews: 167,
            isNew: false,
            isSale: false,
            description: "Classic Duo offers timeless matching watches for couples who appreciate understated luxury. The matching white dials and silver cases create a harmonious pair.",
            features: [
                "Matching White Dials",
                "Silver Steel Cases",
                "Complementary Sizes",
                "Couple Gift Set",
                "Roman Numerals",
                "Date Display",
            ],
            specs: {
                caseMaterial: "316L Steel",
                caseSize: "42mm / 34mm",
                dialColor: "White",
                strapMaterial: "Steel Bracelet",
                movement: "Japanese Quartz",
                waterResistance: "50m",
                warranty: "3 Years",
            },
        },
        {
            id: 3,
            name: "Harmony Collection",
            price: 52999,
            originalPrice: 62999,
            image: "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1587836374828-4dbafa94cf0e?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.9,
            reviews: 98,
            isNew: false,
            isSale: true,
            description: "Harmony Collection represents the perfect union of masculine and feminine design. Each watch complements the other while maintaining individual character.",
            features: [
                "Yin & Yang Design",
                "Automatic Movement",
                "Exhibition Casebacks",
                "Luxury Presentation",
                "Matching Dials",
                "Sapphire Crystals",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "44mm / 36mm",
                dialColor: "Black & White",
                strapMaterial: "Leather",
                movement: "Automatic",
                waterResistance: "100m",
                warranty: "3 Years",
            },
        },
        {
            id: 4,
            name: "Royal Pair",
            price: 72999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1542496658-e33a6d0d50f6?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 5.0,
            reviews: 145,
            isNew: true,
            isSale: false,
            description: "Royal Pair is our premium couples collection featuring rose gold accents and diamond markers. A statement of shared success and refined taste.",
            features: [
                "Rose Gold Accents",
                "Diamond Markers",
                "Premium Leather",
                "Swiss Movement",
                "Luxury Case",
                "VIP Service Card",
            ],
            specs: {
                caseMaterial: "Rose Gold PVD",
                caseSize: "41mm / 33mm",
                dialColor: "Rose Gold",
                strapMaterial: "Crocodile Leather",
                movement: "Swiss Automatic",
                waterResistance: "50m",
                warranty: "5 Years",
            },
        },
        {
            id: 5,
            name: "Timeless Together",
            price: 41999,
            originalPrice: 48999,
            image: "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.7,
            reviews: 189,
            isNew: false,
            isSale: true,
            description: "Timeless Together features minimalist designs that never go out of style. Perfect for couples who believe in enduring elegance.",
            features: [
                "Minimalist Design",
                "Matching Aesthetics",
                "Interchangeable Straps",
                "Gift Packaging",
                "Clean Dials",
                "Slim Profile",
            ],
            specs: {
                caseMaterial: "Stainless Steel",
                caseSize: "40mm / 32mm",
                dialColor: "Silver",
                strapMaterial: "Mesh Steel",
                movement: "Japanese Quartz",
                waterResistance: "30m",
                warranty: "2 Years",
            },
        },
        {
            id: 6,
            name: "Unity Gold",
            price: 59999,
            originalPrice: null,
            image: "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&q=80&w=800",
            images: [
                "https://images.unsplash.com/photo-1622434641406-a158123450f9?auto=format&fit=crop&q=80&w=800",
            ],
            rating: 4.8,
            reviews: 76,
            isNew: false,
            isSale: false,
            description: "Unity Gold celebrates togetherness with matching gold-toned timepieces. The warm hues symbolize the precious nature of your bond.",
            features: [
                "Gold PVD Finish",
                "Matching Set",
                "Premium Gift Box",
                "Champagne Dials",
                "Date Function",
                "Automatic Movement",
            ],
            specs: {
                caseMaterial: "Gold PVD Steel",
                caseSize: "42mm / 34mm",
                dialColor: "Champagne",
                strapMaterial: "Gold Bracelet",
                movement: "Automatic",
                waterResistance: "50m",
                warranty: "3 Years",
            },
        },
    ],
};

export const categoryTitles = {
    men: "Men's Collection",
    women: "Women's Collection",
    couples: "Couples Collection",
};

export const categoryDescriptions = {
    men: "Discover our curated selection of premium men's timepieces, crafted for the modern gentleman.",
    women: "Explore elegant women's watches that blend sophistication with contemporary style.",
    couples: "Celebrate your bond with our exclusive couples watch sets, perfectly paired for two.",
};

export const sortOptions = [
    { value: "featured", label: "Featured" },
    { value: "newest", label: "Newest" },
    { value: "price-low", label: "Price: Low to High" },
    { value: "price-high", label: "Price: High to Low" },
    { value: "rating", label: "Top Rated" },
];

export const categoryHeroImages = {
    men: "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&q=80&w=1920",
    women: "https://images.unsplash.com/photo-1590736969955-71cc94801759?auto=format&fit=crop&q=80&w=1920",
    couples: "https://images.unsplash.com/photo-1515934751635-c81c6bc9a2d8?auto=format&fit=crop&q=80&w=1920",
};
